blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussion
    url: https://github.com/ihw33/StockIQ/discussions
    about: ì¼ë°˜ì ì¸ ì§ˆë¬¸ì´ë‚˜ í† ë¡ 
  - name: ğŸ“š Documentation
    url: https://github.com/ihw33/StockIQ/wiki
    about: ë¬¸ì„œ ë° ê°€ì´ë“œ í™•ì¸